apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Test python app.
  annotations:
    github.com/project-slug: Padmapriya-VN/python-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
spec:
  type: service
  owner: development
  lifecycle: experimental
